services:
  - type: web
    name: lissnify-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Lissnify.settings_production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: elysian-birt.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: lissnify-db
          property: connectionString
      - key: REDIS_URL
        value: redis://default:IDKKkwv9CvxFRw6zaJp1r1JsF4qO8k3C@redis-16891.crce179.ap-south-1-1.ec2.redns.redis-cloud.com:16891
      - key: FRONTEND_URL
        value: https://your-frontend-url.com
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        value: devakoode@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: dqixhlddcbwsbgjx

  - type: pserv
    name: lissnify-db
    plan: free
    databaseName: lissnify
    user: lissnify_user
