# Generated by Django 4.2.23 on 2025-08-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
