# Generated by Django 4.2.23 on 2025-08-18 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('s_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('preference', models.CharField(max_length=255)),
                ('u_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'seeker',
            },
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('l_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('preference', models.CharField(max_length=255)),
                ('u_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'listener',
            },
        ),
    ]
