# Generated by Django 4.2.23 on 2025-08-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listener',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='preference',
        ),
        migrations.AddField(
            model_name='listener',
            name='preferences',
            field=models.ManyToManyField(to='api.category'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='preferences',
            field=models.ManyToManyField(to='api.category'),
        ),
    ]
