# Generated by Django 4.2.23 on 2025-08-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pending', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='api.listener')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='api.seeker')),
            ],
            options={
                'db_table': 'connections',
                'unique_together': {('seeker', 'listener')},
            },
        ),
    ]
