# Generated by Django 4.2.23 on 2025-08-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
