# Generated by Django 4.2.23 on 2025-08-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
